CREATE TABLE
  `article_like` (
    `id` INT UNSIGNED NOT NULL,
    `like_count` INT UNSIGNED NOT NULL DEFAULT '0',
    `last_update` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `id_UNIQUE` (`id`)
  ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
