CREATE TABLE
  `music` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(45) NOT NULL,
    `summary` VARCHAR(45) NOT NULL,
    `url` VARCHAR(45) DEFAULT NULL,
    `img` VARCHAR(45) DEFAULT NULL,
    PRIMARY KEY (`id`)
  ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
