CREATE TABLE
  `score_all` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user` VARCHAR(45) NOT NULL DEFAULT 'unown',
    `score` INT UNSIGNED NOT NULL DEFAULT '0',
    `ip` VARCHAR(45) DEFAULT NULL,
    `version` VARCHAR(255) DEFAULT NULL,
    `create_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `update_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `UNIQUE1` (`user`, `score`, `create_date`)
  ) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
